### PR TITLE
PieChart support with Plot logic.

### PR DESCRIPTION
**Pull request by zdenal**
# Why
Creating PieChart logic based on Plot. Related to this feedback: https://github.com/mindok/contex/pull/48#issuecomment-835665866

PR to update contex-sample: https://github.com/mindok/contex-samples/pull/15

### Example
https://user-images.githubusercontent.com/143357/126164781-01f22a6d-497f-49b1-8978-a76a124b3bb5.mov

### CODE REVIEW

**Comment by zdenal** [comment]
Ola @mindok can you please check this PR if it is ok or let me know what is missing? I did the logic based on conversation mentioned in PR description.

Thanks,
Zdenko

**Comment by mindok** [comment]
Hi @zdenal - apologies for the delay - we're moving house and I got quite distracted. I'm looking now.

**Comment by zdenal** [comment]
Hi @mindok no worries :D ... likewise here ... I have got flooded so I don't know where to turn first :D

**Comment by mindok** [comment]
Ok - this all looks great thanks. The only minor comment is potentially renaming label_slices to be data_labels to be consistent with BarChart, but that won't stop this going in.

Thanks a lot for this work - it's pretty much what I had in mind after I saw the first version.

**Pull request merged**
