### PR TITLE
Introduce simple PieChart.

### PR DESCRIPTION
**Pull request by zdenal**
Simple PieChart support.

I used this nice & simple library recently. I had a need to use some simple pie chart in my stats. This could be a solution.

PR on contex-sample https://github.com/mindok/contex-samples/pull/11

### Screencast on contex-sample

https://user-images.githubusercontent.com/143357/117532763-7c256b80-afe9-11eb-9702-d0f9f68be973.mov

### CODE REVIEW

**Comment by mindok** [comment]
Thanks @zdenal - I had a look through and very happy that you have made such a great start on this. 

What do you think about breaking into two modules, similar to Sparkline and LinePlot? Sparkline is designed to be used in an extremely simple way with very few options and a very simple data structure (similar to what you have here) whereas LinePlot has more options, column mapping capabilities to map the DataSet to what the plot needs. Also, Sparkline returns a full SVG whereas LinePlot returns an SVG fragment for the plot content and a separate one (if required) for the legend and Contex.Plot handles the layout.

So we could have something like:

```elixir
QuickPie.new([{"Cat", 10.0}, {"Dog", 20.0}, {"Hamster", 5.0}])
  |> QuickPie.colours(["aa0000", "00aa00", "0000aa"]) # Optional - only if you don't like the defaults
  |> QuickPipe.draw()
```

and, as a separate module,

```elixir
data = [
  ["Cat", 10.0], 
  ["Dog", 20.0], 
  ["Hamster", 5.0]
]

dataset = DataSet.new(data, ["Pet", "Preference"])

opts = [
  mapping: %{category_col: "Pet", value_col: "Preference"}, 
  colour_palette: ["fbb4ae", "b3cde3", "ccebc5"],
  legend_setting: :legend_right,
  title: "Why dogs are better than cats"
]

Contex.Plot.new(dataset, Contex.PieChart, 600, 400, opts)
```

**Comment by zdenal** [comment]
@mindok I can 👍 . I'll separate it into 2 PRs in sake of simplicity and feedbacks.

Just few question related to `QuickPie` .. it probably won't have a legend rendered correct? Should it have a percentage labels? Or purpose of that will be really so simple as Sparkline ... means it will be used on places as some small indicators/logos where labels doesn't make sense because it would be hard to read.

**Comment by mindok** [comment]
Hi @zdenal - great!
Yes, with "QuickPie" (or better name if you can think of one), I'm thinking very minimal. If you expose the legend function publicly then someone can always draw it if they want to. An example where it might be used is in a table - there may be twenty of them on a screen but they only need to draw the legend once at the top.

And yes, I think labels would be hard to read here. One option is to add a title element to each slice so you can hover over and see the slice name and value if you want.

**Comment by mindok** [comment]
We've merged PR #51 so will close this.

**Pull request closed without merging**
