### PR TITLE
OHLC charts

### PR DESCRIPTION
**Pull request by mindok**
### Overview
- Adds OHLC (open-high-low-close) charts.

### Features
- Option for bull, bear, shadow colors
- Option for zoom levels (so far only body width is affected)
- Optional body border for candles
- Uses `crispEdges` rendering option (looks way better when SVG container size and SVG size match 1:1)
- Colorized bars optional

### Code housekeeping
- Added specs to all functions in `ohlc.ex` (except for protocol implementation ones)
- Improved readability by removing pattern matching from function heads 
- Further improved readability through use of Extructure library

### CODE REVIEW

**Comment by mindok** [comment]
@DaTrader - I have created this PR from your fork. Hopefully this is what you meant about approving a workflow.

**Comment by DaTrader** [comment]
@mindok It's formatted now and I also optimized it a bit not to call a potentially expensive function twice.

**Comment by DaTrader** [comment]
@mindok Can you please approve this?

**Comment by DaTrader** [comment]
> @mindok Can you please approve this?

@mindok ping!

**Comment by mindok** [comment]
Apologies for the delay @DaTrader - merged.

**Pull request merged**
